# Generated by Django 3.2.7 on 2021-09-16 13:52

import amici.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amici', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptOutLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlname', models.CharField(default=amici.models._generate_hex, max_length=32)),
                ('create_date', models.DateField(auto_now=True)),
                ('expired', models.BooleanField(default=False)),
                ('used', models.BooleanField(default=False)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opt_out_links', to='amici.friend')),
            ],
        ),
    ]
